# docker-compose.override.yml (dev)
version: "3.9"
services:
  auto_trader:
    # Keep the container's virtualenv in sync with local requirements before launching
    # the autoreloader so dependency updates are available immediately during dev.
    command:
      [
        "sh",
        "-c",
        "pip install --disable-pip-version-check -r requirements.txt \u0026\u0026 python scripts/run_with_reloader.py --watch /app --ignore /app/logs --ignore /app/state -- python auto_trader.py",
    command:
      [
        "python",
        "scripts/run_with_reloader.py",
        "--watch",
        "/app",
        "--ignore",
        "/app/logs",
        "--ignore",
        "/app/state",
        "--",
        "python",
        "auto_trader.py",
main
      ]
    # Mount the whole repo into /app so edits in PyCharm appear in the container
    volumes:
      - ./:/app:delegated
      - ./logs:/app/logs
      - ./state:/app/state
    environment:
      - PYTHONPATH=/app
    # Auto-restart the script whenever any file under /app changes
