# docker-compose.override.yml (dev)
version: "3.9"
services:
  auto_trader:
    command:
      [
        "python",
        "scripts/run_with_reloader.py",
        "--watch",
        "/app",
        "--ignore",
        "/app/logs",
        "--ignore",
        "/app/state",
        "--",
        "python",
        "auto_trader.py",
      ]
    # Mount the whole repo into /app so edits in PyCharm appear in the container
    volumes:
      - ./:/app:delegated
      - ./logs:/app/logs
      - ./state:/app/state
    environment:
      - PYTHONPATH=/app
    # Auto-restart the script whenever any file under /app changes
