# docker-compose.override.yml (dev)
version: "3.9"
services:
  auto_trader:
    command: ["sh","-lc","python -m watchfiles --filter python --debounce 800 --ignore-paths /app/state --ignore-paths /app/logs --ignore-paths /app/.git --ignore-paths /app/__pycache__ --ignore-glob '*.log' 'python auto_trader.py' /app"]
    # Mount the whole repo into /app so edits in PyCharm appear in the container
    volumes:
      - ./:/app:delegated
      - ./logs:/app/logs
      - ./state:/app/state
    environment:
      - PYTHONPATH=/app
    # Auto-restart the script whenever any file under /app changes